// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP6Cnb7RessFHuLTJg_mMc1XXwfh9L_go',
    appId: '1:200317347986:web:d42937ed9a3eff3cdede4b',
    messagingSenderId: '200317347986',
    projectId: 'solarprojectbackend',
    authDomain: 'solarprojectbackend.firebaseapp.com',
    storageBucket: 'solarprojectbackend.appspot.com',
    measurementId: 'G-3C3MZ7M1T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHOGwraQ-asOBKjejyIDLXYI8LcmYpuuo',
    appId: '1:200317347986:android:134f295b02e27e07dede4b',
    messagingSenderId: '200317347986',
    projectId: 'solarprojectbackend',
    storageBucket: 'solarprojectbackend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu91qyfdc7Din3j04OtwmY-NfhEBzVDjA',
    appId: '1:200317347986:ios:b3932208b3bafb6ddede4b',
    messagingSenderId: '200317347986',
    projectId: 'solarprojectbackend',
    storageBucket: 'solarprojectbackend.appspot.com',
    iosBundleId: 'com.example.solarPower',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu91qyfdc7Din3j04OtwmY-NfhEBzVDjA',
    appId: '1:200317347986:ios:afdb209172f41b16dede4b',
    messagingSenderId: '200317347986',
    projectId: 'solarprojectbackend',
    storageBucket: 'solarprojectbackend.appspot.com',
    iosBundleId: 'com.example.solarPower.RunnerTests',
  );
}
